### PR TITLE
Localisation addition

### PR DESCRIPTION
**Pull request by Jacques44**
Work done by myself as I needed a french localisation
Maybe an answer for the open issue

### CODE REVIEW

**Comment by TotallyInformation** [comment]
Thanks Jacques.

**Comment by Jacques44** [comment]
You're welcome. I'm coding other nodes, I think red-node is a fantastic tool but nodes are not as powerful as I need :-)

**Comment by TotallyInformation** [comment]
Ha ha, I know what you mean. I'm still looking for the ideal scheduling tool. None of the existing ones quite do what I want and what's worse is that they don't seem allow for daylight savings time changes which is a pain.

Still, it's great that it is so easy to create your own.

**Comment by Jacques44** [comment]
You're right. I've just made an "else" path for filter node and published a traffic light node. I've worked this WE for big data support as file node and csv node only work as one_message_is_a_file. The new one are nice but just have to make them at "npm" level !

**Comment by TotallyInformation** [comment]
Ah, that sounds interesting. I look forward to seeing it. I regularly process some horribly large CSV files professionally. I generally end up using Excel with the PowerQuery addin. But NR _should _be great for this kind of processing, it "just" needs a bunch of processing nodes. So if you can turn a file read into effectively a stream, the next parts are to be able to join or merge files based on keys/indexes. Then the ability to filter and group. Finally, the ability to write/append.

No pressure ;-)

**Pull request merged**
