### PR TITLE
Docu rework, version 3.1.0

### PR DESCRIPTION
**Pull request by StephanStS**
Description extended, figures added, examples added.  
Version changed to 3.1.0.  
Changelog.txt added and changes moved from Readme.md.
Configuration property *Output Tz* renamed to *Output Timezone*. 
humanizer.html: Help text extended.

@TotallyInformation: Please review the text changes to ensure that I understood all correct.

### CODE REVIEW

**Comment by TotallyInformation** [comment]
Many thanks Stephan, merged to master. I will try to find time to publish to NPM. I will bump the version and add you as a contributor before then.

**Comment by StephanStS** [comment]
Info: The *Update* section of README.md was moved to Changelog.txt.
Option 1: Add changes to Changelog.txt and remove *Update* section from README.md. 
Option 2: Remove Changelog.txt from the repo.

**Comment by StephanStS** [comment]
Thanks for reviewing and correcting some beautification issues in my docu rework. Nice to see that your docu quality claims are this high.

**Comment by TotallyInformation** [comment]
I use `CHANGELOG.md` when it gets too large for the README.

I will be releasing v4 as soon as I can fix up a couple of other long-standing issues which I'm doing at the moment. That will have your changes plus the others.

Thanks again for the contributions.

**Pull request merged**
